### PR TITLE
Switch to Astro

### PR DESCRIPTION
**Pull request by L1lith**
It's working!! :)

### CODE REVIEW

**Comment by obiot** [comment]
looking at the PR here, there is no index.html at the root ???

**Comment by L1lith** [comment]
> looking at the PR here, there is no index.html at the root ???

There's a build step, it's in the dist folder after running `npm run build`

Edit: does this work for you? Idk how this site gets deployed

**Comment by obiot** [comment]
oh I see. Yeah I guess it's ok, it's actually nice, as you can just work on the website, makes (and collaborate on ) some changes, and one ready we just need to copy the content of the dist folder to the root folder :)

or better, just add master branch, which is maybe cleaner and then copy the content of the dist folder into the gh-pages one.

Note: I realised we still have that old bootstrap branch actually !

**Comment by obiot** [comment]
can you however move back the CNAME file at the root level (should stay there no matter what) and it prevents me from merging (github not liking it)

**Comment by L1lith** [comment]
> can you however move back the CNAME file at the root level (should stay there no matter what) and it prevents me from merging (github not liking it)

How do I do that? Make a new PR? Do you still want a copy of the CNAME in the build folder?

**Comment by L1lith** [comment]
> oh I see. Yeah I guess it's ok, it's actually nice, as you can just work on the website, makes (and collaborate on ) some changes, and one ready we just need to copy the content of the dist folder to the root folder :)
> 
> or better, just add master branch, which is maybe cleaner and then copy the content of the dist folder into the gh-pages one.
> 
> Note: I realised we still have that old bootstrap branch actually !

Oh I read this second. Hmm are you deploying with github pages? If so instead of doing a separate branch we could just build to the `/docs` folder (actually i forget if this works with custom domains). I'm concerned if we push everything into the root the root is gonna get super messy. Though with branches this shouldn't be a problem (but maybe more work?)

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages

```
Custom domains are stored in a CNAME file in the root of your publishing source
```
I think we can consider our build output to be our "publishing source" (the output static site's web root) which is why I put the CNAME in the public folder (that folder gets copied to the build output). We might need to rename dist to docs automatically in the script

**Comment by obiot** [comment]
> > can you however move back the CNAME file at the root level (should stay there no matter what) and it prevents me from merging (github not liking it)
> 
> How do I do that? Make a new PR? Do you still want a copy of the CNAME in the build folder?

I think you just need to make a new commit on your branch and it should be visible here ?

**Comment by L1lith** [comment]
> > > can you however move back the CNAME file at the root level (should stay there no matter what) and it prevents me from merging (github not liking it)
> > 
> > 
> > How do I do that? Make a new PR? Do you still want a copy of the CNAME in the build folder?
> 
> I think you just need to make a new commit on your branch and it should be visible here ?

I don't think we need to put it in the root though, if we change our website root to the docs folder we don't need to change our setup at all just copy the build output

**Comment by L1lith** [comment]
I've just fixed a styling issue and a few other minor bugs I saw. I also made it so if you run `npm run build` it will automatically generate the `docs` folder for us (which you can configure in the repo's settings to be the root for the site). If this doesn't work I'm not opposed to copying it to root I just thought this might be easier?

Edit: i just added an extra CNAME for redundancy but I don't think it's actually required
Edit 2: I also pre-built the site in the docs folder so you don't have to do that. All you'd have to do is merge and set the pages root to `/docs` I think

**Comment by obiot** [comment]
> > > > can you however move back the CNAME file at the root level (should stay there no matter what) and it prevents me from merging (github not liking it)
> > > 
> > > 
> > > How do I do that? Make a new PR? Do you still want a copy of the CNAME in the build folder?
> > 
> > 
> > I think you just need to make a new commit on your branch and it should be visible here ?
> 
> I don't think we need to put it in the root though, if we change our website root to the docs folder we don't need to change our setup at all just copy the build output

you have to, this is how Github managed custom domains: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
> Under "Custom domain", type your custom domain, then click Save. This will create a commit that adds a CNAME file in the root of your publishing source.

**Comment by obiot** [comment]
I think we will need to do this in different steps (once this PR is merged), but basically the right way should be:
- create back a `main` or dev branch where this whole code is
- publish to `gh-pages` (root level)
- ultimately use a GitHub workflow to automatically publish to `gh-pages` when building the website from the "main" repository

**Comment by L1lith** [comment]
> I think we will need to do this in different steps (once this PR is merged), but basically the right way should be:
> 
>     * create back a `main` or dev branch where this whole code is
> 
>     * publish to `gh-pages` (root level)
> 
>     * ultimately use a GitHub workflow to automatically publish to `gh-pages` when building the website from the "main" repository

Alright, you can do it either way but I think the domain thing might be unrelated:
[See here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

When I'm managing my github pages for my library theres a "source" box above the domain that allows you to specify a subdir. Do whatever works though, I'm excited for Astro :)

Edit: I hope you don't mind but I also added eslint and prettier integration so we could enforce consistent styling

**Comment by obiot** [comment]
> See here

sorry, just looking at it now, super busy weekend (yesterday was a bank holiday here), and I had a couple of pending commit on melonJS itself, and most of all I was trying to figure out why using www.melonjs.org still throws a Certificate issue....  (head banging against the wall stuff)

Indeed I did not know about this, so in this case which one should be the folder to specify here, `public` or `docs` ?

**Comment by obiot** [comment]
> > See here
> 
> .... and most of all I was trying to figure out why using [www.melonjs.org](http://www.melonjs.org) still throws a Certificate issue.... (head banging against the wall stuff)
> 

and finally it works, so Pull Request time now !

**Comment by L1lith** [comment]
> Indeed I did not know about this, so in this case which one should be the folder to specify here, public or docs ?

Use `docs` please 😃 

> and finally it works, so Pull Request time now !

Do I need to do anything or can we merge it now?

**Comment by obiot** [comment]
> 😃
> 
> > and finally it works, so Pull Request time now !
> 
> Do I need to do anything or can we merge it now?

no need to to anything, but I had to go to a meeting, so I'll merge later once I'm back, and use the `docs` folder :)

I'll delete the old boostrap branch too !

**Comment by obiot** [comment]
@L1lith merged and published ! 

https://melonjs.org

looks good globally, but there are a few issues I noticed :
- the bigger issue is the main logo missing :)
- in the feature section, the title and features are mis-aligned
- lots of empty space between section ?


also, can you maybe explain in the README how the whole new website work, how to modify it and how to publish ?  I got it that gh-pages will built it out of the docs folder now, but now the rest is like black magic for me :P I could not even find where to fix the missing logo between src and docs :)

**Comment by obiot** [comment]
I actually fixed the logo, but it was an case sensitive issue (filename was "Logo.svg", but was referenced as "logo.svg")

**Pull request merged**
